import { ArtifactDocument } from './ArtifactDocument.tsx';
import type { Approval } from '@pitchcrew/core';
import { type ArtifactPages, resumePageWarning } from '../helpers.ts';

export function ArtifactPreview({ approval, pages }: { approval: Approval; pages: ArtifactPages }) {
  const warning = resumePageWarning(approval.artifacts ?? [], pages);
  return approval.artifacts?.length ? (
    <section className="my-3 space-y-2">
      <h3>Generated documents</h3>
      <p className="quiet">
        Formatted documents lay out headings, lists and links. Plain text documents show the
        Markdown literally. Export includes these exact generated bytes.
      </p>
      {warning ? <p className="font-semibold text-ochre">{warning}</p> : null}
      {approval.artifacts.map((artifact) => (
        <ArtifactDocument
          approval={approval}
          artifact={artifact}
          pages={pages}
          key={artifact.name}
        />
      ))}
    </section>
  ) : null;
}
