import { ArtifactDocument } from './ArtifactDocument.tsx';
import type { Approval } from '@pitchcrew/core';

export function ArtifactPreview({ approval }: { approval: Approval }) {
  return approval.artifacts?.length ? (
    <section className="my-3 space-y-2">
      <h3>Generated documents</h3>
      <p className="quiet">
        Documents render the reviewed Markdown as literal text. Export includes these exact
        generated bytes.
      </p>
      {approval.artifacts.map((artifact) => (
        <ArtifactDocument approval={approval} artifact={artifact} key={artifact.name} />
      ))}
    </section>
  ) : null;
}
