import { smokeChatPanels } from './smoke-chat-panels.ts';
/** Verify conversation navigation lives in the shell and remains useful with an icon sidebar. */
export const smokeConversations = `(async () => {
  document.querySelector('a[href="/"]')?.click();
  if (!await waitFor(() => location.pathname === '/')) throw new Error('Conversation creation did not start from Board.');
  document.querySelector('button[aria-label="New conversation"]')?.click();
  if (!await waitFor(() => !!document.querySelector('#conversation-title'))) throw new Error('New conversation dialog did not open from the app sidebar.');
  const title = document.querySelector('#conversation-title');
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(title, 'Fictional sidebar conversation');
  title.dispatchEvent(new Event('input', { bubbles: true }));
  await waitFor(() => !title.form.querySelector('button[type="submit"]').disabled);
  title.form.requestSubmit();
  const created = await waitFor(() => document.querySelector('.chat-heading h2')?.textContent === 'Fictional sidebar conversation' && !document.querySelector('#conversation-title'));
  const rail = document.querySelector('nav[aria-label="Conversations"]');
  const singleSidebar = !!rail?.closest('[data-slot="sidebar-container"]') && !document.querySelector('.chat-workspace nav') && getComputedStyle(document.querySelector('.chat-workspace')).gridTemplateColumns.trim().split(/\\s+/).length === 1;
  document.querySelector('.chat-runtime')?.click();
  await waitFor(() => !!document.querySelector('#conversation-model-reasoning'));
  const inheritedFields = document.querySelector('#conversation-runtime')?.textContent.includes('Use agent default') && document.querySelector('#conversation-model')?.value.includes('Use agent default') && document.querySelector('#conversation-model-reasoning')?.textContent.includes('Use agent default');
  [...document.querySelectorAll('.chat-editor button')].find((button) => button.textContent === 'Save runtime')?.click();
  const runtimeClosed = await waitFor(() => !document.querySelector('.chat-editor'));
  const snapshotAfterRuntime = await fetch('/api/snapshot', { headers: { 'x-pitchcrew-client': 'ui' } }).then((response) => response.json());
  const configured = snapshotAfterRuntime.conversations.find((item) => location.pathname === '/chat/' + item.id)?.configurations.scout;
  const runtimeDefaults = !!inheritedFields && runtimeClosed && !!configured && Object.keys(configured).length === 0;
  const chatPanels = await ${smokeChatPanels};
  const search = document.querySelector('input[aria-label="Search conversations and messages"]');
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(search, 'Fictional sidebar');
  search.dispatchEvent(new Event('input', { bubbles: true }));
  const filtered = await waitFor(() => rail.querySelectorAll('.conversation-link').length === 1 && rail.querySelector('.conversation-link')?.getAttribute('aria-current') === 'page');
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(search, '');
  search.dispatchEvent(new Event('input', { bubbles: true }));
  await waitFor(() => rail.querySelectorAll('.conversation-link').length > 1);
  document.querySelector('main [data-slot="sidebar-trigger"]')?.click();
  const collapsed = await waitFor(() => !!document.querySelector('button[aria-label="Open conversations"]'));
  document.querySelector('button[aria-label="Open conversations"]')?.click();
  const expanded = await waitFor(() => document.activeElement === document.querySelector('nav[aria-label="Conversations"] input'));
  document.querySelector('nav[aria-label="Conversations"] a[href="/chat/scout"]')?.click();
  const navigated = await waitFor(() => location.pathname === '/chat/scout' && !!document.querySelector('textarea[aria-label="Message Scout"]'));
  return { created, singleSidebar, runtimeDefaults, chatPanels, filtered, collapsed, expanded, navigated };
})()`;
