export const capabilityLabels = {
  messageAgents: 'Message crew members',
  invokeAgents: 'Invoke itself and other roles',
  manageWorkflow: 'Change job workflows',
  reviewPipeline: 'Review applications, outcomes and every crew role',
  proposeCrewChanges: 'Propose reviewed changes to other roles',
  manageRoutines: 'Create, edit and delete scheduled actions',
  maintainProfile: 'Detect watched profile changes and propose reviewed updates',
  readApplications: 'Search all tracked applications and evidence',
  trackApplications: 'Reconcile application status from verified Gmail evidence',
  discoverJobs: 'Scan your saved job sources and add new matching leads',
  github: 'Read GitHub repositories, files and issues',
  gmail: 'Search and read Gmail',
  drive: 'Search Drive and read files and Docs',
  calendar: 'Read Google Calendar events',
  sheets: 'Read Google Sheets ranges',
  assessForms: 'Assess inspected application forms',
  recordSubmissions: 'Record approved submission attempts and evidence',
  computerUse: 'Use a local browser with approval for each interaction',
};

export const capabilityDefaults = {
  messageAgents: true,
  invokeAgents: true,
  manageWorkflow: true,
  manageRoutines: true,
  maintainProfile: false,
  readApplications: false,
  trackApplications: false,
  reviewPipeline: false,
  proposeCrewChanges: false,
  discoverJobs: false,
  github: false,
  gmail: false,
  drive: false,
  calendar: false,
  sheets: false,
  computerUse: false,
  assessForms: false,
  recordSubmissions: false,
};
