export const eventKindLabels = {
  user_input: 'User questions',
  conversation: 'Conversations',
  conversation_session: 'Runtime sessions',
  chat_request: 'Queued messages',
  agent_memory: 'Agent memories',
  pipeline_review: 'Pipeline reviews',
  card: 'Jobs',
  role: 'Roles',
  run: 'Runs',
  approval: 'Packet approvals',
  message: 'Messages',
  proposal: 'Role suggestions',
  task: 'Follow-ups',
  routine: 'Routines',
  tracking_signal: 'Application evidence',
  tracking_scan: 'Email tracking scans',
  skill: 'Skills',
  skill_proposal: 'Skill suggestions',
  computer_approval: 'Browser approvals',
  profile_proposal: 'Profile updates',
  form_assessment: 'Form assessments',
  submission_attempt: 'Submission receipts',
} as const;

export const actorLabels: Record<string, string> = {
  user: 'You',
  demo: 'Demo runtime',
  system: 'Pitchcrew',
  mcp: 'Crew tools',
  scout: 'Scout',
  writer: 'Writer',
  reviewer: 'Reviewer',
};
